version: '3.8'

services:
  main:
    build: .
    volumes:
      - .:/django
    ports:
      - '8000:8000'
    image: main:django
    container_name: todo-list
    command: python manage.py runserver 0.0.0.0:8000